COAL:
  max_price: 100
  min_price: 10
  price: 81
  count: 19
  max_count: 1000
  step: 10
DIAMOND:
  max_price: 100
  min_price: 10
  price: 10
  count: 1
  max_count: 1000
  step: 10
IRON_INGOT:
  max_price: 100
  min_price: 10
  price: 97
  count: 1
  max_count: 1000
  step: 10
GOLD_INGOT:
  max_price: 100
  min_price: 10
  price: 91
  count: 1
  max_count: 1000
  step: 10